cache: bundler
language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database geo_lclark_test;' -U postgres
rvm:
  - 2.2.5
notifications:
    slack: watzekdi:GytGd6DHh3hzm3YVnLbREmWt
