version: '3.4'

volumes:
  index-precreate:
  db:

services:

  app:
    build: .
    image: watzek/compass
    volumes:
      - index-precreate:/usr/src/geoblacklight/solr/conf
    environment:
      SOLR_URL: http://index:8983/solr/compass
    depends_on:
      - db
      - db_migrate
      - index
    ports:
      - 3000:3000

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data

  index:
    image: solr
    command: bash -c "sleep 20 && solr-precreate compass /precreate"
    volumes:
      - index-precreate:/precreate

  mq:
    image: rabbitmq:management
    ports:
      - 3001:15672

  workers:
    build: .
    image: watzek/compass
    command: bash -c "sleep 20 && WORKERS=GeoblacklightMessaging::GeoblacklightEventHandler rake sneakers:run"
    depends_on:
      - db
      - db_migrate
      - mq

  db_migrate:
    build: .
    image: watzek/compass
    command: bash -c "sleep 20 && rake db:migrate"
    depends_on:
      - db
