version: '2'

services:

  app:
    build: .
    environment:
      SOLR_URL: http://geo.lclark.edu:8983/solr/geoblacklight
      SUBMIT_URL: http://geo.lclark.edu/submit

  db:
    image: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data

  mq:
    image: rabbitmq:management
    ports:
      - 3001:15672

  web:
    extends: app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - db_migrate
    ports:
      - 3000:3000

  workers:
    extends: app
    command: bash -c "sleep 20 && WORKERS=GeoblacklightMessaging::GeoblacklightEventHandler rake sneakers:run"
    depends_on:
      - db
      - db_migrate
      - mq

  db_migrate:
    extends: app
    command: rake db:migrate
    depends_on:
      - db
