defaults: &defaults
  events:
    server: <%= ENV.fetch('RABBIT_SERVER') { 'amqp://localhost:5672' } %>
    exchange:
      geoblacklight: 'gbl_events'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
